services:
  app:
    build: .
    restart: always
    mem_limit: 256m
    memswap_limit: 512m
    environment:
      - NODE_ENV=production
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - default

networks:
  default:
